### ISSUE TITLE
Any way to test the installation?

### ISSUE THREAD

**Issue by JSSaini** [zoubohao/Deepurify#11]
Hello, it would be helpful to test the tool after installation to see everything run smooth. I am getting following error kindly let me know if you have any idea from where it might be coming from? 
Thank you. 
Kind regards,
Jaspreet

```
Traceback (most recent call last):
  File "/home/saini/miniconda3/envs/deepurify/lib/python3.8/site-packages/Deepurify/Utils/LabelBinsUtils.py", line 885, in labelBinsFolder
    state = torch.load(modelWeightPath, map_location=torch.device(device))
  File "/home/saini/miniconda3/envs/deepurify/lib/python3.8/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/saini/miniconda3/envs/deepurify/lib/python3.8/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
          2 / 195603                              ^M          3 / 195603                              ^M          4 / 195603                              ^M          5 / 195603                              ^M          6 / 195603                              ^M          7 / 195603                              ^M          8 / 195603                              ^M          9 / 195603                              ^M          10 / 195603                             ^M          11 / 195603                             ^M          12 / 195603                             ^M          13 / 195603                             ^M          14 / 195603                             ^M          15 / 195603                             ^M          16 / 195603                             ^M          17 / 195603                             ^M          18 / 195603                             ^M          19 / 195603                             ^M          20 / 195603                             ^M          21 / 195603                             ^M          22 / 195603                             ^M          23 / 195603                             ^M          24 / 195603                             ^M          25 / 195603                             ^M          26 / 195603                             ^M          27 / 195603                             ^M          28 / 195603                             ^M          29 / 195603                             ^M          30 / 195603                             ^M          31 / 195603                  
```

**Comment by zoubohao** [comment]
Hi JSSaini

Thanks for using Deepurify. You loaded an empty model weight file. 

Please do not use the '[Deepurify-DB](https://github.com/zoubohao/Deepurify/tree/master/Deepurify-DB)' file in the GitHub. Those files are all empty.  Please download the file from the link: https://drive.google.com/file/d/1FXpxoXFYHcX9QAFe7U6zfM8YjalxNLFk/.

Please follow the section "Download Model Weight and Other Files for Running" for downloading and installation.

**Comment by zoubohao** [comment]
You can use these MAGs for testing "https://github.com/ericcombiolab/Deepurify/tree/main/demo_inputs" with the following command: 

```
deepurify clean  -i ./input_folder/ -o ./output_folder/ --bin_suffix fasta --gpu_num 1 --each_gpu_threads 1 --db_folder_path /path/of/this/Deepurify-DB/
```

**Comment by JSSaini** [comment]
Sorry, I mean testing the installion if all the tools are installed correctly and databases are in order.

**Comment by JSSaini** [comment]
Kindly see the attached log file for error. It seems to be stuck with Checkm2 because of lack of quality report. 

Already did the following recommended step. 

Do not forget to download the database files for CheckM2 !!! and set environmental variable CHECKM2DB using: export CHECKM2DB="/path/to/database/uniref100.KO.1.dmnd"
[M-2163126-error.txt](https://github.com/user-attachments/files/17365188/M-2163126-error.txt)

**Comment by zoubohao** [comment]
This error occurs since checkm2 needs an empty folder. You can delete all files in 'Deepurify_output_folder' and run the command again.

**Comment by JSSaini** [comment]
Tried another set of MAGs, got different error this time. Kindly see the attached log. Thank you. 
[M-2163701-error.txt](https://github.com/user-attachments/files/17380271/M-2163701-error.txt)

**Comment by zoubohao** [comment]
This error occurs since there is a low case "g" in your sequences. Please make sure your sequences only contain upper case "A", "T", "C", "G". Please delete all files in 'Deepurify_output_folder' and run the command again. We will fix this bug in next update version.

**Comment by JSSaini** [comment]
I see, thank you for letting me know.
