### ISSUE TITLE
Deepurify-DB file is incomplete

### ISSUE THREAD

**Issue by LiangLifeng** [zoubohao/Deepurify#7]
Hello, Deepurify is a useful tool. But the latest files “Deepurify-DB/CheckPoint/GTDB-clu-last.pth” and “Deepurify-DB/HMM/hmm_models.hmm” in the Deepurify-DB folder on Github are empty, causing the failure of Deepurify version 2.3.0. Would you provide these two files, please?

**Comment by zoubohao** [comment]
Hello

These two files are too large to upload to GitHub. Please download the Deepurify-DB.zip from this link: "https://drive.google.com/file/d/1FXpxoXFYHcX9QAFe7U6zfM8YjalxNLFk/view?usp=sharing".

Best

**Comment by LOYINuts** [comment]
Hello. Sorry to bother you. The file pointed to by this link does not exist.
