### ISSUE TITLE
Error occurs when the value of gpu_num is 0.

### ISSUE THREAD

**Issue by LiangLifeng** [zoubohao/Deepurify#8]
In version 2.3.2, when the value of gpu_num is 0 in Deepurify/cli.py script, line 337: s_ratio = 1. / float(args.gpu_num) will have issues.

**Comment by zoubohao** [comment]
Thanks for using Deepurify. I will fix the bug right now.

**Comment by zoubohao** [comment]
The bug has been fixed.
![bugfix](https://github.com/zoubohao/Deepurify/assets/35212019/5b3b3548-a03f-4310-96f4-c89088e16d90)

**Comment by zoubohao** [comment]
Download the 2.3.3 version
