### ISSUE TITLE
error of Deepurify/cli.py  "--contigs path" 

### ISSUE THREAD

**Issue by LiangLifeng** [zoubohao/Deepurify#9]
Hi, the error in executing "re-bin" was caused by a missing underscore in the path "--contigs path" at line 194 of Deepurify/cli.py. In line 381 of Deepurify/cli.py, the error occurred because the 'Namespace' object does not have the attribute 'contigs_path'.

**Comment by zoubohao** [comment]
Hi
Thanks for using Deepurify. Could you please give me more details? What is the command you used?

**Comment by zoubohao** [comment]
Sorry for the bug. I know how to fix it now........

**Comment by zoubohao** [comment]
![bug_fix](https://github.com/zoubohao/Deepurify/assets/35212019/b3a7ae74-26d2-4483-b8a1-9fe3260b2cf0)

The bug has been fixed.
